### ISSUE TITLE
hi remember me i am tm3 from mars survive on minetest

### ISSUE THREAD

**Issue by tanmayameher** [linushsao/marsu_game-linus-v0.2#1]
Your read me file is completely empty and there is no descriptions.txt to explain things to user what are the things here in this mod. Best is to write a description. If you allow me to make a file name description.txt and write details on it. I will try to make it in a complete manual/tutorial fashion. Also, you can include the link to this mod in github in the help or first appear window section in that game.

Regards
Tanmaya Meher aka tm3

**Comment by linushsao** [comment]
of course,thank you ,tm3.

 i'm glade to hear your plan to make manual/tutorial.  

here is a SERVER GUID BOOD MOD:
https://forum.minetest.net/viewtopic.php?f=11&t=13366

maybe your great manual/tutorial could be not only put in github,but also put in game for everyone(could be bought from NPC?...^^!).i believe new players will need manual/tutorial in this survival game.

.i'm just a server menteiner,but players like you/juli/yang know more detail about mar than me.

**Comment by tanmayameher** [comment]
Thanks man! But how can i make a server guide i don't have i think that give privs. its needed to give me and change the server guide. BTW i have never made a server guide yet don't know how to make it. Is it easy? like putting title and content etc.

**Comment by linushsao** [comment]
Oh,we'll make ingame server guide according to your manual(well done!).we have to insert your writing into the lua codes of that server guide mod.so even  me can't write server guide in gaming,it's the work of server side,not client...@@a.

**Comment by linushsao** [comment]
I have read your request from email,I'm outside now,will be back home soon.(I could not handle pull request from mobile app ...@@!)

**Comment by tanmayameher** [comment]
that's ok. i will try to update as much stuff as possible.
