### ISSUE TITLE
clean the repo

### ISSUE THREAD

**Issue by cpdef** [linushsao/marsu_game-linus-v0.2#16]
i would like to do 2 things:
1. make some mod-manage folders like:
- minetest_game contains all mods from minetest_game
- technical contains mesecons, pipeworks, digilines, technics etc.
- plantlive contains all plat and farming stuff
- others
- mars contains the mars_pack

2. Add to every mod a file like version.txt containing
- date of mod download, 
- version 
- link, if on github to the branch

What do u think about that?

**Comment by linushsao** [comment]
hi,juli

2018-03-07 6:19 GMT+08:00 cpdef <notifications@github.com>:

> i would like to do 2 things:
>
>    1. make some mod-manage folders like:
>
>
>    - minetest_game contains all mods from minetest_game
>
> it's ok.mods from latest minetest_game or?

>
>    - technical contains mesecons, pipeworks, digilines, technics etc.
>    - plantlive contains all plat and farming stuff
>
> it's nice,but why? for easy to be managed or?

>
>    - others
>    - mars contains the mars_pack
>
>  mars contains the mars_pack? what's that?

>
>
>
>    1. Add to every mod a file like version.txt containing
>
>
>    - date of mod download,
>    - version
>    - link, if on github to the branch
>
> of course,it's very nice.

>
>
> What do u think about that?
>
 thanks for your feedback,juli.

**Comment by cpdef** [comment]
`it's ok.mods from latest minetest_game or?
 it's nice,but why? for easy to be managed or?`
both only for easy management, we have latest minetest_game also installed already.
`mars_pack? what's that?` 
thats the modpack we have installed for mars :)

`    1. Add to every mod a file like version.txt containing
    - date of mod download,
    - version
    - link, if on github to the branch
 of course,it's very nice.`
ok then we can start that.

**Comment by tanmayameher** [comment]
yeah sorting them will do. We can even sort the mods which are only for decoration to a  single folder.

Putting dates and version of mod is a good idea. We can update or track any recent update in the original branch.

**Comment by cpdef** [comment]
Yes sure we can sort it more, its even better. 
The categories i said have been only those i could think of in the Moment i wrote it ...

**Comment by tanmayameher** [comment]
If it is just moving and sorting into folder and writing a file with their names etc. in not so complicated codes or somewhat like that; i can do it too. But, Linus can do it too.

**Comment by cpdef** [comment]
i would prefer sort and then edit ....
