### ISSUE TITLE
Server crash by calling weather

### ISSUE THREAD

**Issue by tanmayameher** [linushsao/marsu_game-linus-v0.2#3]
Server crashed at about 20:50 IST Nov 18th 2016 by calling
`/weather` command. Please rectify it bro.
Plus i have a lots of message for you in the game. Log in to game to see :)

See the below section from irc when it happened. I called the `/weather` command again to verify. Sorry about that. :wink: 

> (08:45:38  IST) MarsServer: *** ximeeeee joined the game
(08:46:45  IST) MarsServer: *** ximeeeee left the game
(08:48:51  IST) MarsServer: *** efe joined the game
(08:49:06  IST) MarsServer left the room (quit: Quit: Game shutting down.).
(08:50:16  IST) MarsServer [~Minetest@139.59.238.211] entered the room.
(08:50:16  IST) mode (+v MarsServer) by ChanServ
(08:50:23  IST) MarsServer: *** tm3 joined the game
(08:50:27  IST) tm3: hi
(08:50:43  IST) MarsServer: *** bpatlarge joined the game
(08:51:00  IST) MarsServer: <tm3> did server crash lol
(08:51:07  IST) MarsServer: <tm3> or may be daily reboot
(08:51:18  IST) MarsServer: <bpatlarge> i asked for the weather
(08:51:32  IST) MarsServer: <bpatlarge> then it crashed
(08:51:33  IST) MarsServer: <tm3> what? weather?
(08:51:50  IST) MarsServer: <tm3> i still don't get it asking for weather don't crash it
(08:51:57  IST) MarsServer: <bpatlarge> yeah the command "/weather"
(08:52:00  IST) MarsServer: <tm3> oh
(08:52:05  IST) MarsServer: <tm3> i need to see it wait
(08:52:08  IST) MarsServer left the room (quit: Client Quit).
(08:53:11  IST) MarsServer [~Minetest@139.59.238.211] entered the room.
(08:53:11  IST) mode (+v MarsServer) by ChanServ
(08:53:13  IST) MarsServer: *** bpatlarge joined the game
(08:54:05  IST) MarsServer: *** Kahoun115 joined the game
(08:56:46  IST) MarsServer: *** Kahoun115 left the game (Timed out)
(08:57:06  IST) MarsServer: *** tm3 joined the game
(08:57:35  IST) MarsServer: <tm3> reported and generated an issue in github about that. Admin will see it soon and rectify
(08:57:58  IST) MarsServer: <tm3> until then please don't use that command
(08:58:12  IST) MarsServer: <bpatlarge> ok, i won't aask for the weather again...
(08:58:35  IST) MarsServer: <tm3> its ok its not your fault
(08:58:39  IST) MarsServer: <tm3> its the server problem
(08:58:56  IST) MarsServer: <tm3> he will soon rectify it i will notify you when you can use it again

**Comment by linushsao** [comment]
tks for your issue,i'll test all command of mymonth.
