### ISSUE TITLE
Hi Linus. Sorry to interrupt but are you doing something because total server is not online

### ISSUE THREAD

**Issue by tanmayameher** [linushsao/marsu_game-linus-v0.2#5]
I am trying to login (Dt. 28th Nov 2016) through irc and in game . But the server is not online. What extra code you have added i don't know but it has boomed everything. In irc, Mars Server is not online but chanserv is online try to login and see. That's why when i am login ingame too it's not showing anything. everything is shown as unknown item. try going ingame you will know. The entire Mars Server is not at all online. I think the code you have updated by using code from Gundul is the problem because you use irc.freenode.net where as jungle server (gundul's server) uses chat.freenode.net and uses chanserv. So, the total system has crashed and Mars Server is offline now. Try to come in irc. we will talk about it more.

**Comment by linushsao** [comment]
hey,bro. take it easy. Server is working fine now. tks very much for your caring about this game server. 

see you~
